# Generated by Django 5.0.6 on 2024-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('btn_one', models.URLField()),
                ('btn_two', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slider_item', models.ManyToManyField(to='restaurantapp.slideritem')),
            ],
        ),
    ]
