# Generated by Django 5.0.6 on 2024-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(default='slider/slider.jpeg', upload_to='slider/'),
        ),
    ]
