# Generated by Django 5.0.6 on 2024-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_slideritem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='slider/slider.jpeg', upload_to='slider/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greating_text', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('about_item', models.ManyToManyField(to='restaurantapp.aboutitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
