# Generated by Django 5.0.6 on 2024-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_aboutservice_aboutus_about_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutservice',
            name='image',
            field=models.ImageField(upload_to='icon'),
        ),
    ]
