# Generated by Django 5.0.6 on 2024-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_alter_aboutservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('offer', models.CharField(max_length=20)),
                ('offer_price', models.FloatField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('btn', models.URLField()),
                ('image_one', models.ImageField(default='slider/slider.jpeg', upload_to='image_one')),
                ('image_two', models.ImageField(default='slider/slider.jpeg', upload_to='image_two')),
                ('is_spcial', models.BooleanField(default=False)),
            ],
        ),
    ]
