# Generated by Django 5.0.6 on 2024-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliciousMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sanacks', 'Sanacks'), ('Desert', 'Desert'), ('Dinner', 'Dinner'), ('Freshfood', 'Freshfood')], max_length=50)),
                ('food_image', models.ImageField(default='food.jpg', upload_to='FoodImage')),
                ('food_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
